### ISSUE TITLE
Put the font and save buttton at the top

### ISSUE THREAD

**Issue by kashsuks** [kashsuks/textEditor#2]

**Comment by kashsuks** [comment]
`Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tkinter/__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/Users/ksukshavasi/textEditor/main.py", line 42, in handle_configure
    elif not fullscreen and root.state() == 'normal':
             ^^^^^^^^^^
NameError: name 'fullscreen' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tkinter/__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/Users/ksukshavasi/textEditor/main.py", line 42, in handle_configure
    elif not fullscreen and root.state() == 'normal':
             ^^^^^^^^^^
NameError: name 'fullscreen' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tkinter/__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/Users/ksukshavasi/textEditor/main.py", line 42, in handle_configure
    elif not fullscreen and root.state() == 'normal':
             ^^^^^^^^^^
NameError: name 'fullscreen' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tkinter/__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/Users/ksukshavasi/textEditor/main.py", line 42, in handle_configure
    elif not fullscreen and root.state() == 'normal':
             ^^^^^^^^^^
NameError: name 'fullscreen' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tkinter/__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/Users/ksukshavasi/textEditor/main.py", line 42, in handle_configure
    elif not fullscreen and root.state() == 'normal':
             ^^^^^^^^^^
NameError: name 'fullscreen' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tkinter/__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/Users/ksukshavasi/textEditor/main.py", line 42, in handle_configure
    elif not fullscreen and root.state() == 'normal':
             ^^^^^^^^^^
NameError: name 'fullscreen' is not defined`


Trying to fix this error currently

**Comment by kashsuks** [comment]
**Edit** The error has been fixed, It was due to me not initializing the `fullscreen` variable before usage
